version: '3'

networks:
  symfony-brain-bites:

services:
    nginx-service:
        image: nginx:latest
        container_name: nginx-container
        volumes:
            - ./app:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${NGINX_PORT}:80
        networks:
            - symfony-brain-bites
        depends_on:
            - php-service
            - mysql-service

    php-service:
        build:
            context: ./php
            args:
                HOSTNAME: ${HOSTNAME}
                EMAIL: ${GIT_EMAIL}
                NAME: ${GIT_NAME}
        container_name: php-container
        volumes:
            - ./app:/var/www/app
        ports:
            - ${PHP_PORT}:9000
        networks:
            - symfony-brain-bites
        depends_on:
            -   mysql-service

    phpmyadmin-service:
        image: phpmyadmin
        container_name: phpmyadmin-container
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: mysql-service
            PMA_PORT: 3306
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        networks:
            - symfony-brain-bites
        depends_on:
            - mysql-service

    mysql-service:
        image: mysql:8
        container_name: mysql-container
        volumes:
            - ./mysql:/var/lib/mysql
        command:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
        restart:
            always
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - symfony-brain-bites

    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        networks:
            - symfony-brain-bites