version: '3'

networks:
    symfony-amronas:

services:
    nginx-service:
        image: nginx:latest
        container_name: nginx-amronas
        volumes:
            - ./app:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${NGINX_PORT}:80
        networks:
            - symfony-amronas
        depends_on:
            - php-service
            - mysql-service
        environment:
            - TZ=${TIME_ZONE}

    php-service:
        build:
            context: ./php
            args:
                TIME_ZONE: ${TIME_ZONE}
        container_name: php-amronas
        volumes:
            - ./app:/var/www/app
        ports:
            - ${PHP_PORT}:9000
        networks:
            - symfony-amronas
        depends_on:
            - mysql-service

    phpmyadmin-service:
        image: phpmyadmin
        container_name: phpmyadmin-amronas
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: mysql-service
            PMA_PORT: 3306
            TZ: ${TIME_ZONE}
        restart: always
        networks:
            - symfony-amronas
        depends_on:
            - mysql-service

    mysql-service:
        image: mysql:8
        container_name: mysql-amronas
        volumes:
            - ./mysql:/var/lib/mysql
        command:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            TZ: ${TIME_ZONE}
        restart:
            always
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - symfony-amronas

    node-service:
        image: node:latest
        container_name: node-amronas
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        networks:
            - symfony-amronas
        environment:
            - TZ=${TIME_ZONE}