twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/theme.html.twig']
    globals:
        is_login_enabled: '%is_login_enabled%'

when@test:
    twig:
        strict_variables: true
